language: python
python:
- 3.9
- 3.8
- 3.7
- 3.6
install: pip install -U tox-travis
script: tox
deploy:
  provider: pypi
  distributions: sdist bdist_wheel
  user: __token__
  password:
    secure: cveO8PzS8YUqUKzkiKNzHDO6aufoJoF8GRc0MR1ti+3/UWEK0j1Eh3OSnxoNVc86eMMP1vd87dLL74CO9+5u67jJ2fQG9ouLhge+bOcPvlAK59nGUobueOc0LXG7EtagLdC0+mbDVoae3BAEyTwfDT4FqUWxUAOb8t4Yx8f+MkAsv1wDGZFamD8hqP4QIM4lkkU7PL3qUs0PomVrz8YrxNzXM0TpQ/iLn5Ch3tTKLjdOu6gQDcluB32OoEe4PC5GobSOV6a8Jgl0ABj1RnZCWv58g9hm14WnVN5zHVZ/TrHi/6wDs/oWOyyEkGfFR/FNeGNarWrG+Egh2A5F7oc8nj/g/kRFIt9VKiUWJ606p/zTHxu9sZpzac0ThqriVePCQtRNX/GBHyN9y5IUiEU5xvBvHA4o4I90zwBMmQRXXBLZQiNOTyQH49f7yXW3AAICK/fRSBBmG5XPNuK8Gj5hvBjx2eFlaz/S3HEKMp765rhHHoyROMvLr8auCxHbQmS1yKDZ5QC4RumGbc6ZBrSWw9egPDd0MUoEpUqXdXsOTn5qC5iR5HZEKSJmB4CUpiPEL8/YaKjOIVwWh0BgbHepFYcgZPMJsObIfjJ9SeewEdHrYSj08FYTxO/eCicJiP3MijeupS7ltRNuLm9j7y0+3QHpe6XxBayP1gyzZtd/sqc=
  on:
    tags: true
    repo: mtannaan/asn1vnparser
    python: 3.9
