language: python
python:
    - 3.9
    - 3.8
    - 3.7
    - 3.6
install: pip install -U tox-travis
script: tox
deploy:
    provider: pypi
    distributions: sdist bdist_wheel
    user: __token__
    password:
        secure: d34xMXvFnM4zy+QqzpKPrs/FeGci48LWk2eYyQ5nnAg6QwPutz62pwWKda2PDf/MkmyvS6DczQtv6oukrfUNJ5bepEhks/1lGLx/QtlmbY7IJUR4McfqCn9xFvyHzDIFEIjyTaBKRE1putHq/XBq+E1I06pARjJnw3wjn6lQ7mm5Z1vXLk8y+Gi1x/C8phOecdNT0s78zWWOOdYHXc1HvVdo4XOtzieCSC8r3A6DFDnxOlI8G0leKZxbCbrmIg2+z76/1zNA1Qi/Oq41X+bLhMycvZ9pl6oVLdjPKwWGFp4Ez9EJSBH97gARqQEOQ+miBe8c+juzyQF+t9ndQ1KPOfHULf92whi4Rame+t3VIMB1gAjOUCmkTVrTYnXWiLvlFiyZUEAp8YK7ADz43QZXu+71niusE6C6/6q7uCVTdMHFDW1d3y/BkhCSstlM0/GqVzBgp3cxCOwxgEr/+mjkeSF87N3gXhPtbWgxlBJ0vwY80xqr4IhwG4zosF6r1EuohCT7FeQ6YijiDATzQ9slmm+3wNm/VEIdyygqlyPuBcXW9ruJUljspX4qDITwoJoQzTZ1PtRbyANcXQm8jg2ryYjSPMTLdSfFv0gNxLLFhu76Qo181cK9aZd6SB0ZvOqBMYN5ZUttRMmmcaUPEQ5pEjElevBT30nIZ2tr7Bx/Pys=
    on:
        tags: true
        repo: mtannaan/asn1vnparser
        python: 3.9
